apiVersion: v1
kind: Pod          
metadata:
  name: pod-app-02 
  labels:
    app: pod-app-02  
spec:
  containers:
    - name: cntr-httpd   
      image: httpd:latest
      ports:
        - containerPort: 80
